# -*- coding: utf-8 -*-
"""TESTE_1_Exercicio_2_Texto_Juridico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17FwuYqtBzKyZRX7AJ3-PqQO35VUCQbez
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Exemplo de base de dados com textos jurídicos
data = {
    'id': [1, 2, 3, 4],
    'texto': [
        "Decisão judicial sobre contrato de trabalho.",
        "Petição inicial em ação de danos morais.",
        "Documento legal relacionado a direitos autorais.",
        "Decisão judicial sobre direito do consumidor."
    ]
}

# Convertendo os dados em um DataFrame
df = pd.DataFrame(data)

# Passo 1: Vetorização dos textos usando TF-IDF
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(df['texto'])

# Passo 2: Escolha de um texto de referência (por exemplo, o primeiro texto)
texto_referencia = tfidf_matrix[0]

# Passo 3: Cálculo da similaridade do cosseno entre o texto de referência e os outros textos
similaridade = cosine_similarity(texto_referencia, tfidf_matrix)

# Passo 4: Ordenação dos textos por similaridade
similaridade_scores = list(enumerate(similaridade[0]))
similaridade_scores = sorted(similaridade_scores, key=lambda x: x[1], reverse=True)

# Exibição dos textos mais semelhantes
print("Textos mais semelhantes ao texto de referência:\n")
for idx, score in similaridade_scores:
    print(f"Texto ID: {df.iloc[idx]['id']}, Similaridade: {score:.4f}")
    print(f"Conteúdo: {df.iloc[idx]['texto']}\n")